# Generated by Django 2.2.5 on 2019-09-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaConsultants', '0003_login_loginresponsefail_loginresponsesuccess_profileresponsesuccess_register_registerresponsefail_re'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobResponseSuccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='jobSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_terms', models.CharField(max_length=50)),
                ('category_1', models.CharField(max_length=50)),
                ('category_2', models.CharField(max_length=50)),
                ('order_by', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('min_price', models.CharField(max_length=50)),
                ('max_price', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('page_amount', models.IntegerField()),
                ('page_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='makeBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=50)),
                ('bid_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('time_sent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='messageSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='projectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('date_created', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('business_id', models.CharField(max_length=50)),
                ('current_bid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='registerJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=50)),
                ('project_title', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=50)),
                ('project_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='simpleProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('business_id', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('current_bid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='uploadJobPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=50)),
                ('image_byte_array', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='uploadSuccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userValidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='viewConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=50)),
                ('session_token', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='viewJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('session_token', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='viewProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
    ]
