# Generated by Django 2.2.5 on 2019-09-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaConsultants', '0003_login_loginresponsefail_loginresponsesuccess_profileresponsesuccess_register_registerresponsefail_re'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('session_token', models.CharField(max_length=50)),
                ('block_status', models.CharField(max_length=50)),
                ('date_created', models.IntegerField()),
                ('profile_picture', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='conversationData',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='loginResponseFail',
        ),
        migrations.DeleteModel(
            name='loginResponseSuccess',
        ),
        migrations.DeleteModel(
            name='profileResponseSuccess',
        ),
        migrations.DeleteModel(
            name='register',
        ),
        migrations.DeleteModel(
            name='registerResponseFail',
        ),
        migrations.DeleteModel(
            name='registerResponseSuccess',
        ),
        migrations.DeleteModel(
            name='responseFail',
        ),
        migrations.DeleteModel(
            name='responseSuccess',
        ),
        migrations.DeleteModel(
            name='userBlock',
        ),
    ]
