# Generated by Django 2.2.5 on 2019-09-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('session_token', models.CharField(max_length=50)),
                ('block_status', models.CharField(max_length=50)),
                ('date_created', models.IntegerField()),
                ('profile_picture', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
