# Generated by Django 2.2.5 on 2019-09-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190920_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dp',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='buss_name',
            field=models.CharField(default='company', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='My bio here ....'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='name@ua.com', max_length=254),
        ),
    ]
