# Generated by Django 2.2.6 on 2019-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(default='My Job', max_length=50)),
                ('date_created', models.TextField(blank=True, max_length=500)),
                ('job_summary', models.TextField(blank=True, max_length=500)),
                ('business_id', models.TextField(blank=True, max_length=500)),
                ('current_bid', models.TextField(blank=True, max_length=500)),
                ('project_photos', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
