# Generated by Django 2.2.5 on 2019-09-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
