# Generated by Django 2.2.5 on 2019-10-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20191008_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='business',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_summary',
            new_name='job_description',
        ),
        migrations.AddField(
            model_name='job',
            name='bid_amount',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
