# Generated by Django 2.2.5 on 2019-10-08 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20191008_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
