# Generated by Django 2.2.5 on 2019-10-09 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20191008_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='business_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
