# Generated by Django 2.2.5 on 2019-10-09 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0005_auto_20191009_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_name',
        ),
        migrations.AddField(
            model_name='job',
            name='business_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='project_name',
            field=models.CharField(default='My Project', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='business_name',
            field=models.TextField(max_length=500),
        ),
    ]
