# Generated by Django 2.2.5 on 2019-10-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20191009_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='business_id',
            new_name='business',
        ),
    ]
