# Generated by Django 2.2.6 on 2019-10-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20191025_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='premium',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
