# Generated by Django 2.2.5 on 2019-10-10 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20191009_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='project_photos',
        ),
        migrations.AlterField(
            model_name='job',
            name='business_name',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='jobPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('title', models.CharField(default='Title', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.job')),
            ],
        ),
    ]
