# Generated by Django 2.2.5 on 2019-10-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20191010_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobphotos',
            name='image',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jobphotos',
            name='title',
            field=models.TextField(default='Title', max_length=100),
        ),
    ]
