# Generated by Django 2.2.5 on 2019-10-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20191010_0126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobPhotos',
            new_name='project_photos',
        ),
    ]
