# Generated by Django 2.2.5 on 2019-10-10 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20191010_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='project_photos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='job.project_photos'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='project_photos',
            unique_together={('image', 'title')},
        ),
        migrations.RemoveField(
            model_name='project_photos',
            name='project',
        ),
    ]
