# Generated by Django 2.2.5 on 2019-10-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20191010_0156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project_photos',
            unique_together=set(),
        ),
    ]
