# Generated by Django 2.2.6 on 2019-10-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20191010_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='business_name',
        ),
    ]
