# Generated by Django 2.2.6 on 2019-10-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_job_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='business_name',
        ),
    ]
