# Generated by Django 2.2.6 on 2019-10-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_job_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='business_name',
        ),
    ]
