# Generated by Django 2.2.6 on 2019-10-12 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_remove_job_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_photos',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_photos', to='job.job'),
        ),
    ]
