# Generated by Django 2.2.6 on 2019-10-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_auto_20191013_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='photoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='project_photos',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project_photos',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_photos', to='job.job'),
        ),
        migrations.AlterField(
            model_name='project_photos',
            name='title',
            field=models.TextField(blank=True, default='Title', max_length=100),
        ),
    ]
