# Generated by Django 2.2.6 on 2019-10-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_auto_20191013_0848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photoUpload',
        ),
    ]
