swagger: "2.0"
info:
  version: "1.0.0"
  title: "UA Consultants"
host: "13.211.139.75:3800"
basePath: "/"
tags:
  - name: "user"
    description: "Operations about user"
  - name: "job"
    description: "All things job related"
  - name: "chat"
    description: "All things messaging related"
  - name: "noti"
    description: "All things notifications"
schemes:
  - "http"
paths:
  /user/register:
    post:
      tags:
        - "user"
      summary: "Register a new user"
      description: ""
      operationId: "register"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/Register"
      responses:
        200:
          description: "User registered successfully"
          schema:
            $ref: "#/definitions/RegisterResponseSuccess"
        400:
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/RegisterResponseFail"
  /user/login:
    post:
      tags:
        - "user"
      summary: "Login a user"
      description: ""
      operationId: "login"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/Login"
      responses:
        200:
          description: "User logged in successfully"
          schema:
            $ref: "#/definitions/LoginResponseSuccess"
        400:
          description: "Invalid Login Details"
          schema:
            $ref: "#/definitions/LoginResponseFail"
  /user/block:
    get:
      tags:
        - "user"
      summary: "Blocks user by id"
      description: ""
      operationId: "block"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/UserBlock"
      responses:
        200:
          description: "User successfully blocked"
          schema:
            $ref: "#/definitions/ResponseSuccess"
        400:
          description: "Issue blocking user"
          schema:
            $ref: "#/definitions/ResponseFail"
  /user/profile:
    get:
      tags:
        - "user"
      summary: "Get user by user name"
      description: ""
      operationId: "getUserByName"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/ViewProfile"
      responses:
        200:
          description: "Successfully recieved profile"
          schema:
            $ref: "#/definitions/ProfileResponseSuccess"
        400:
          description: "Could not find user"
          schema:
            $ref: "#/definitions/ResponseFail"

  /job/search:
    get:
      tags:
        - "job"
      summary: "Search for a job"
      description: ""
      operationId: "search"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/JobSearch"
      responses:
        200:
          description: "Search successful"
          schema:
            $ref: "#/definitions/JobResponseSuccess"
        400:
          description: "Search error"
          schema:
            $ref: "#/definitions/ResponseFail"
  /job/photo/upload:
    post:
      tags:
        - "job"
      summary: "Upload a job photo"
      description: ""
      operationId: "jobphotoupload"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/UploadJobPhoto"
      responses:
        200:
          description: "Photo uploaded successfully"
          schema:
            $ref: "#/definitions/UploadSuccess"
        400:
          description: "Photo upload failed"
          schema:
            $ref: "#/definitions/ResponseFail"

  /job/register:
    post:
      tags:
        - "job"
      summary: "Register a job"
      description: ""
      operationId: "jobregister"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/RegisterJob"
      responses:
        200:
          description: "Job registered successfully"
          schema:
            $ref: "#/definitions/ResponseSuccess"
        400:
          description: "Job failed to register"
          schema:
            $ref: "#/definitions/ResponseFail"
  /job/view:
    get:
      tags:
        - "job"
      summary: "View a job by id"
      description: ""
      operationId: "jobview"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/ViewJob"
      responses:
        200:
          description: "View job success"
          schema:
            $ref: "#/definitions/Projects"
        400:
          description: "View job error"
          schema:
            $ref: "#/definitions/ResponseFail"

  /job/bid:
    post:
      tags:
        - "job"
      summary: "Bid on a job"
      description: ""
      operationId: "jobbid"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/MakeBid"
      responses:
        200:
          description: "User made a bid successfully"
          schema:
            $ref: "#/definitions/ResponseSuccess"
        400:
          description: "Bid failed"
          schema:
            $ref: "#/definitions/ResponseFail"
  /chat/getall:
    get:
      tags:
        - "chat"
      summary: "Gets all conversation data"
      description: ""
      operationId: "chatget"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/UserValidate"
      responses:
        200:
          description: "Retrieved data successfully"
          schema:
            $ref: "#/definitions/ConversationList"
        400:
          description: "An issue occured getting chats"
          schema:
            $ref: "#/definitions/ResponseFail"
  /chat/conversation:
    get:
      tags:
        - "chat"
      summary: "Get messages with user by id"
      description: ""
      operationId: "getmessages"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/ViewConversation"
      responses:
        200:
          description: "Chat data recieved successfully"
          schema:
            $ref: "#/definitions/ChatData"
        400:
          description: "Failed to recieve conversation"
          schema:
            $ref: "#/definitions/ResponseFail"
  /chat/sendmessage:
    post:
      tags:
        - "chat"
      summary: "Send message to user, starts conversation if first message"
      description: ""
      operationId: "sendmessage"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/MessageSend"
      responses:
        200:
          description: "Message sent successfully"
          schema:
            $ref: "#/definitions/ResponseSuccess"
        400:
          description: "Message failed to send"
          schema:
            $ref: "#/definitions/ResponseFail"
  /healthcheck:
    get:
      tags:
        - "healthcheck"
      summary: "Tests server connection"
      description: ""
      operationId: "healthcheck"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Message sent successfully"
          schema:
            $ref: "#/definitions/ResponseSuccess"
        400:
          description: "Message failed to send"
          schema:
            $ref: "#/definitions/ResponseFail"
definitions:
  Register:
    type: "object"
    properties:
      email:
        type: "string"
      name:
        type: "string"
      business_name:
        type: "string"
      password:
        type: "string"
  Login:
    type: "object"
    properties:
      email:
        type: "string"
        example: "ben2"
      password:
        type: "string"
        example: "ben000"
  RegisterResponseSuccess:
    type: "object"
    properties:
      session_token:
        type: "string"
      status:
        type: "string"
        example: "success"
  RegisterResponseFail:
    type: "object"
    properties:
      error:
        type: "string"
      status:
        type: "string"
        example: "failure"
      username:
        type: "string"
  LoginResponseSuccess:
    type: "object"
    properties:
      session_token:
        type: "string"
      status:
        type: "string"
        example: "success"
  LoginResponseFail:
    type: "object"
    properties:
      error:
        type: "string"
      status:
        type: "string"
        example: "failure"
  UserBlock:
    type: "object"
    properties:
      session_token:
        type: "integer"
        format: "int64"
      block_id:
        type: "string"
  ResponseSuccess:
    type: "object"
    properties:
      status:
        type: "string"
        example: "success"
  ResponseFail:
    type: "object"
    properties:
      error:
        type: "string"
      status:
        type: "string"
        example: "failure"
  ProfileResponseSuccess:
    type: "object"
    properties:
      business_name:
        type: "string"
        example: "Bob's Timber"
      date_created:
        type: "integer"
        example: 1568267256799
      profile_picture:
        type: "string"
        example: "https://via.placeholder.com/150C/O"
      description:
        type: "string"
        example: "Genuine timber work at genuine prices"
      user_projects:
        type: "array"
        items:
          $ref: '#/definitions/Projects'
      open_bids:
        type: "array"
        items:
          $ref: '#/definitions/Projects'
  Projects:
    type: "object"
    properties:
      project_name:
        type: "string"
        example: "Skirting board installation"
      date_created:
        type: "integer"
        example: 1568267256799
      description:
        type: "string"
      business_id:
        type: "string"
      business_name:
        type: "string"
        example: "Paul's skirtings"
      location:
        type: "string"
        example: "Newtown, NSW"
      current_bid:
        type: "integer"
      bid_amount:
        type: "integer"
      project_photos:
        type: "array"
        items:
          $ref: '#/definitions/ProjectPhoto'
  SimpleProjects:
    type: "object"
    properties:
      project_name:
        type: "string"
        example: "Skirting board installation"
      description:
        type: "string"
      business_id:
        type: "string"
      business_name:
        type: "string"
        example: "Paul's skirtings"
      location:
        type: "string"
        example: "Newtown, NSW"
      current_bid:
        type: "integer"
        example: "2500"
      bid_amount:
        type: "integer"
        example: "5"
      project_photo:
        $ref: '#/definitions/ProjectPhoto'
  ProjectPhoto:
    type: "object"
    properties:
      image:
        type: "string"
        example: "https://images.unsplash.com/photo-1556020685-ae41abfc9365?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60"
      title:
        type: "string"
  JobSearch:
    type: "object"
    properties:
      search_terms:
        type: "string"
      category_1:
        type: "string"
      category_2:
        type: "string"
      order_by:
        type: "string"
      loacation:
        type: "string"
      min_price:
        type: "string"
      max_price:
        type: "string"
      distance:
        type: "string"
      page_amount:
        type: "integer"
        example: 25
      page_number:
        type: "integer"
        example: 0
  JobResponseSuccess:
    type: "object"
    properties:
      amount:
        type: "integer"
        example: 1
      total:
        type: "integer"
        example: 1
      results:
        type: "array"
        items:
          $ref: '#/definitions/SimpleProjects'
  RegisterJob:
    type: "object"
    properties:
      session_token:
        type: "string"
      project_title:
        type: "string"
      project_description:
        type: "string"
      project_location:
        type: "string"
      project_photos:
        type: "array"
        items:
          $ref: '#/definitions/ProjectPhoto'
  UploadJobPhoto:
    type: "object"
    properties:
      session_token:
        type: "string"
      image_byte_array:
        type: "string"
  UploadSuccess:
    type: "object"
    properties:
      url:
        type: "string"
  UserValidate:
    type: "object"
    properties:
      session_token:
        type: "string"
  MakeBid:
    type: "object"
    properties:
      session_token:
        type: "string"
      bid_value:
        type: "string"
      current_bid:
        type: "string"
      job_id:
        type: "string"
  ConversationData:
    type: "object"
    properties:
      user_name:
        type: "string"
        example: "Albert"
      business_name:
        type: "string"
        example: "Bob's Kitchens"
      profile_picture:
        type: "string"
        example: "https://via.placeholder.com/150C/O"
      job_link:
        type: "string"
      conversation_id:
        type: "string"
      last_message:
        $ref: '#/definitions/Message'
  ConversationList:
    type: "array"
    items:
      $ref: '#/definitions/ConversationData'
  Message:
    type: "object"
    properties:
      user_id:
        type: "string"
      message:
        type: "string"
        example: "This is a test message that is pretty long"
      time_sent:
        type: "integer"
        example: 1568267256799
  MessageSend:
    type: "object"
    properties:
      session_token:
        type: "string"
      message:
        type: "string"
  ChatData:
    type: "object"
    properties:
      conversation:
        $ref: '#/definitions/ConversationData'
      messages:
        type: "array"
        items:
          $ref: '#/definitions/Message'
  ViewProfile:
    type: "object"
    properties:
      user_id:
        type: "string"
  ViewJob:
    type: "object"
    properties:
      user_id:
        type: "string"
      session_token:
        type: "string"
  ViewConversation:
    type: "object"
    properties:
      conversation_id:
        type: "string"
      session_token:
        type: "string"
